# Generated by Django 5.2.17 on 2026-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyconnection',
            name='battery_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familyconnection',
            name='device_name',
            field=models.CharField(default='Unknown Device', max_length=100),
        ),
    ]
